"""
generate_branch_report.py - Programmatic Git Branch & Address Manifest Auditor

Exposes Git metadata and standardizes contract addresses mapped inside
public/settlement.json across active branch targets.
"""

import os
import json
import subprocess
from typing import Dict


def run_git_cmd(args: list) -> str:
    """Safely executes a git CLI command and returns clean stdout."""
    try:
        res = subprocess.run(
            ["git"] + args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True
        )
        return res.stdout.strip()
    except (subprocess.SubprocessError, FileNotFoundError):
        return "UNKNOWN_BRANCH_OR_STATE"


def extract_active_manifest() -> Dict[str, str]:
    """Parses local settlement.json and extracts current contract states."""
    manifest_path = "public/settlement.json"
    default_resp = {
        "ProvenanceLedger": "NOT_DEPLOYED",
        "ProvenanceRegistry": "NOT_DEPLOYED",
        "DataAssetRegistry": "NOT_DEPLOYED"
    }

    if not os.path.exists(manifest_path):
        return default_resp

    try:
        with open(manifest_path, "r", encoding="utf-8") as file_handle:
            data = json.load(file_handle)
            # Support both flat and legacy nested configurations
            if "contracts" in data:
                return {
                    "ProvenanceLedger": data["contracts"].get("Intelligence_Ledger", "NOT_FOUND"),
                    "ProvenanceRegistry": data["contracts"].get("Provenance_Registry", "NOT_FOUND"),
                    "DataAssetRegistry": data["contracts"].get("Data_Asset_Registry", "NOT_FOUND")
                }
            return {
                "ProvenanceLedger": data.get("ProvenanceLedgerAddress", "NOT_FOUND"),
                "ProvenanceRegistry": data.get("ProvenanceRegistryAddress", "NOT_FOUND"),
                "DataAssetRegistry": data.get("DataAssetRegistryAddress", "NOT_FOUND")
            }
    except (json.JSONDecodeError, IOError) as err:
        return {"ParsingError": str(err)}


def generate_reports() -> None:
    """Programmatically builds JSON and Markdown branch artifacts."""
    print("[Wurk] Generating programmatic branch and token report...")

    # 1. Gather environmental and git metadata
    active_branch = run_git_cmd(["rev-parse", "--abbrev-ref", "HEAD"])
    commit_hash = run_git_cmd(["rev-parse", "HEAD"])
    author_email = run_git_cmd(["log", "-1", "--format=%ae"])

    addresses = extract_active_manifest()

    report_data = {
        "token_name": "Epiphany Intelligence Token",
        "token_symbol": "EIT",
        "git_metadata": {
            "active_branch": active_branch,
            "commit_hash": commit_hash,
            "last_commit_author": author_email
        },
        "deployed_contract_addresses": addresses
    }

    # 2. Write structured JSON report
    json_out = "artifacts/branch_report.json"
    os.makedirs(os.path.dirname(json_out), exist_ok=True)
    with open(json_out, "w", encoding="utf-8") as f:
        json.dump(report_data, f, indent=4)
    print(f"[Wurk] Deployed structured JSON manifest to: {json_out}")

    # 3. Write human-readable Markdown dossier
    md_out = "artifacts/BRANCH_REPORT.md"
    md_content = f"""# EPIPHANY PROTOCOL - BRANCH & TOKEN AUDIT REPORT

**Active Git Branch:** {active_branch}
**Commit Signature:** 0x{commit_hash[:16]}...
**Last Committer:** {author_email}

---

### 1. Token Specifications
* **Protocol Name:** Epiphany Liquid Economy
* **Central Utility Token:** Epiphany Intelligence Token (EIT)
* **Token Decimals:** 18 ($10^{{18}}$ base units)

---

### 2. Deployed Contract Addresses (Staged on Branch)
Below are the compiled smart contract addresses tracked inside [settlement.json](file:///app/public/settlement.json) for this specific tracking branch:
* **ProvenanceLedger (Token):** `{addresses.get("ProvenanceLedger", "NOT_FOUND")}`
* **ProvenanceRegistry:** `{addresses.get("ProvenanceRegistry", "NOT_FOUND")}`
* **DataAssetRegistry:** `{addresses.get("DataAssetRegistry", "NOT_FOUND")}`

---
Generated by Epiphany Automated Registry Auditor.
"""

    with open(md_out, "w", encoding="utf-8") as f:
        f.write(md_content)
    print(f"[Wurk] Deployed markdown audit dossier to: {md_out}")


if __name__ == "__main__":
    generate_reports()
